datasources:
  postgres:
    url: jdbc:postgresql://${Name}Postgres.${Name}:5432/kestra
    driverClassName: org.postgresql.Driver
    username: ${DatabaseUser}
    password: ${DatabasePassword}
kestra:
  server:
    basic-auth:
      enabled: false
      username: admin@kestra.io
      password: kestra
  repository:
    type: postgres
  storage:
    type: local
    local:
      base-path: "/app/storage"
  secret:
    type: vault
    vault:
      address: "http://${Name}Vault:8200"
      token:
        token: ${VaultToken}      
  queue:
    type: postgres
  tasks:
    tmp-dir:
      path: /tmp/kestra-wd/tmp
  url: http://localhost:8080/