datasources:
  postgres:
    url: jdbc:postgresql://${Name}Postgres.${Name}:5432/kestra
    driverClassName: org.postgresql.Driver
    username: ${PostgresUser}
    password: ${PostgresPassword}
kestra:
  server:
    basic-auth:
      enabled: false
      username: admin@kestra.io
      password: kestra
  repository:
    type: postgres
  storage:
    type: local
    local:
      base-path: "/app/storage"
  queue:
    type: postgres
  tasks:
    tmp-dir:
      path: /tmp/kestra-wd/tmp
  url: http://localhost:8080/